#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONFIG_PATH = path.join(ROOT, "data", "task-config.json");
const OUT_PATH = path.join(ROOT, "shortcuts", "baba-farm-mobile-runner.xml");

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function pickRandom(items) {
  return items[Math.floor(Math.random() * items.length)];
}

function replaceParams(baseUrl, taskItem, paramObj) {
  let url = baseUrl;
  for (const [key, values] of Object.entries(paramObj || {})) {
    url = url.replace(new RegExp(key, "g"), pickRandom(values));
  }
  String(taskItem).split(" ").forEach((value, idx) => {
    if (!value) return;
    url = url.replace(new RegExp(`占位参数${idx + 1}`, "g"), value);
  });
  return url;
}

function buildTaskUrls(config) {
  const taskNames = config.activity?.taskList || [];
  const urls = [];
  for (const taskName of taskNames) {
    const task = config.taskData?.[taskName]?.task;
    if (!task) continue;
    for (const item of task.item || []) {
      const baseUrl = replaceParams(task.baseurl, item, task.param);
      urls.push(`taobao${baseUrl}`);
    }
  }
  return urls;
}

function assertLocalOnlyXml(xml) {
  const remoteConfigMarkers = [
    "is.workflow.actions.downloadurl",
    "bbnc.json",
    "raw.gitcode.com",
  ];
  for (const marker of remoteConfigMarkers) {
    if (xml.includes(marker)) {
      throw new Error(`Generated shortcut unexpectedly references remote configuration: ${marker}`);
    }
  }
}

function urlListXml(urls) {
  return urls.map((url) => `            <dict>
              <key>WFItemType</key>
              <integer>0</integer>
              <key>WFValue</key>
              <dict>
                <key>Value</key>
                <dict>
                  <key>string</key>
                  <string>${escapeXml(url)}</string>
                </dict>
                <key>WFSerializationType</key>
                <string>WFTextTokenString</string>
              </dict>
            </dict>`).join("\n");
}

function buildShortcutXml(urls) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>WFWorkflowActions</key>
  <array>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>芭芭农场本地任务入口：从内置任务深链列表中随机选择并打开一个任务。</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>Shortcuts generated by Shortcuts Playground. Prompt: 仅使用本快捷指令内置的任务深链列表运行；不下载或解析远程配置。</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>从固化的本地任务列表中选择一条深链，供下一步在淘宝中打开。</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.list</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFItems</key>
        <array>
${urlListXml(urls)}
        </array>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.getitemfromlist</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>UUID</key>
        <string>22222222-2222-4222-8222-222222222222</string>
        <key>WFItemSpecifier</key>
        <string>Random Item</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>Open: 打开随机选择的任务深链。</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.openurl</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFInput</key>
        <dict>
          <key>Value</key>
          <dict>
            <key>OutputName</key>
            <string>Item from List</string>
            <key>OutputUUID</key>
            <string>22222222-2222-4222-8222-222222222222</string>
            <key>Type</key>
            <string>ActionOutput</string>
          </dict>
          <key>WFSerializationType</key>
          <string>WFTextTokenAttachment</string>
        </dict>
      </dict>
    </dict>
  </array>
  <key>WFWorkflowClientVersion</key>
  <string>2700.0.4</string>
  <key>WFWorkflowHasOutputFallback</key>
  <false/>
  <key>WFWorkflowIcon</key>
  <dict>
    <key>WFWorkflowIconGlyphNumber</key>
    <integer>61440</integer>
    <key>WFWorkflowIconStartColor</key>
    <integer>431817727</integer>
  </dict>
  <key>WFWorkflowImportQuestions</key>
  <array/>
  <key>WFWorkflowMinimumClientVersion</key>
  <integer>900</integer>
  <key>WFWorkflowMinimumClientVersionString</key>
  <string>900</string>
  <key>WFWorkflowName</key>
  <string>芭芭农场本地入口</string>
  <key>WFWorkflowOutputContentItemClasses</key>
  <array/>
  <key>WFWorkflowTypes</key>
  <array/>
</dict>
</plist>
`;
}

function main() {
  const config = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8"));
  const urls = buildTaskUrls(config);
  if (!urls.length) throw new Error("No task URLs generated");
  const xml = buildShortcutXml(urls);
  assertLocalOnlyXml(xml);
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, xml);
  console.log(`Generated ${OUT_PATH}`);
  console.log(`Embedded local task URLs: ${urls.length}`);
  console.log("Remote JSON actions: none");
}

main();
