#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const TARGETS = {
  "baba-farm": {
    configPath: path.join(ROOT, "data", "task-config.json"),
    outputPath: path.join(ROOT, "shortcuts", "baba-farm-mobile-runner.xml"),
    workflowName: "芭芭农场本地入口",
    intro: "芭芭农场本地任务入口：从第一个任务开始，按顺序逐个打开全部内置深链。",
  },
  "farm-bargain": {
    configPath: path.join(ROOT, "data", "farm-bargain-task-config.json"),
    outputPath: path.join(ROOT, "shortcuts", "farm-bargain-mobile-runner.xml"),
    workflowName: "农场砍价",
    intro: "农场砍价本地任务入口：从第一个任务开始，按顺序逐个打开全部内置深链。",
  },
  "kkl": {
    configPath: path.join(ROOT, "data", "kkl-task-config.json"),
    outputPath: path.join(ROOT, "shortcuts", "kkl-mobile-runner.xml"),
    workflowName: "红包砍砍乐",
    intro: "红包砍砍乐本地任务入口：从第一个任务开始，按顺序逐个打开全部内置深链。",
  },
  "jump-618": {
    configPath: path.join(ROOT, "data", "jump-618-task-config.json"),
    outputPath: path.join(ROOT, "shortcuts", "jump-618-mobile-runner.xml"),
    workflowName: "淘宝618跳一跳",
    intro: "淘宝618跳一跳本地任务入口：从第一个任务开始，按顺序逐个打开全部内置深链。",
  },
  "hhle": {
    configPath: path.join(ROOT, "data", "hhle-task-config.json"),
    outputPath: path.join(ROOT, "shortcuts", "hhle-mobile-runner.xml"),
    workflowName: "红包花花乐",
    intro: "红包花花乐本地任务入口：从第一个任务开始，按顺序逐个打开全部内置深链。",
  },
};

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function pickRandom(items) {
  return items[Math.floor(Math.random() * items.length)];
}

function replaceParams(baseUrl, taskItem, paramObj) {
  let url = baseUrl;
  for (const [key, values] of Object.entries(paramObj || {})) {
    url = url.replace(new RegExp(key, "g"), pickRandom(values));
  }
  String(taskItem).split(" ").forEach((value, idx) => {
    if (!value) return;
    url = url.replace(new RegExp(`占位参数${idx + 1}`, "g"), value);
  });
  return url;
}

function buildTaskUrls(config) {
  const taskNames = config.activity?.taskList || [];
  const urls = [];
  const waits = [];
  for (const taskName of taskNames) {
    const task = config.taskData?.[taskName]?.task;
    if (!task) continue;
    if (Number.isFinite(Number(task.wait))) waits.push(Number(task.wait));
    for (const before of task.before || []) {
      if (Number.isFinite(Number(before.wait))) waits.push(Number(before.wait));
      if (before.url) urls.push(`taobao${replaceParams(before.url, "", task.param)}`);
    }
    for (const item of task.item || []) {
      const baseUrl = replaceParams(task.baseurl, item, task.param);
      urls.push(`taobao${baseUrl}`);
    }
  }
  return {
    urls,
    waitSeconds: waits.length ? Math.max(...waits) : 20,
  };
}

function assertLocalOnlyXml(xml) {
  const remoteConfigMarkers = [
    "is.workflow.actions.downloadurl",
    "bbnc.json",
    "raw.gitcode.com",
  ];
  for (const marker of remoteConfigMarkers) {
    if (xml.includes(marker)) {
      throw new Error(`Generated shortcut unexpectedly references remote configuration: ${marker}`);
    }
  }
}

function urlListXml(urls) {
  return urls.map((url) => `            <dict>
              <key>WFItemType</key>
              <integer>0</integer>
              <key>WFValue</key>
              <dict>
                <key>Value</key>
                <dict>
                  <key>string</key>
                  <string>${escapeXml(url)}</string>
                </dict>
                <key>WFSerializationType</key>
                <string>WFTextTokenString</string>
              </dict>
            </dict>`).join("\n");
}

function buildShortcutXml(target, urls, waitSeconds) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>WFWorkflowActions</key>
  <array>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>${escapeXml(target.intro)}</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>Shortcuts generated by Shortcuts Playground. Prompt: 仅使用本快捷指令内置的任务深链列表运行；不下载或解析远程配置。</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>按内置任务列表顺序逐个处理，每次打开一个深链后等待 ${waitSeconds} 秒。</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.list</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>UUID</key>
        <string>11111111-1111-4111-8111-111111111111</string>
        <key>WFItems</key>
        <array>
${urlListXml(urls)}
        </array>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>- Repeat with Each 使用上面的完整任务列表
- Repeat Item 是当前要打开的深链
- 每次打开后等待 ${waitSeconds} 秒，再继续下一项</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.repeat.each</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>GroupingIdentifier</key>
        <string>44444444-4444-4444-8444-444444444444</string>
        <key>WFControlFlowMode</key>
        <integer>0</integer>
        <key>WFInput</key>
        <dict>
          <key>Value</key>
          <dict>
            <key>OutputName</key>
            <string>List</string>
            <key>OutputUUID</key>
            <string>11111111-1111-4111-8111-111111111111</string>
            <key>Type</key>
            <string>ActionOutput</string>
          </dict>
          <key>WFSerializationType</key>
          <string>WFTextTokenAttachment</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>把当前 Repeat Item 转成 URL，然后打开它。</string>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.url</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>UUID</key>
        <string>33333333-3333-4333-8333-333333333333</string>
        <key>WFURLActionURL</key>
        <dict>
          <key>Value</key>
          <dict>
            <key>attachmentsByRange</key>
            <dict>
              <key>{0, 1}</key>
              <dict>
                <key>Type</key>
                <string>Variable</string>
                <key>VariableName</key>
                <string>Repeat Item</string>
              </dict>
            </dict>
            <key>string</key>
            <string>￼</string>
          </dict>
          <key>WFSerializationType</key>
          <string>WFTextTokenString</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.openurl</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFInput</key>
        <dict>
          <key>Value</key>
          <dict>
            <key>OutputName</key>
            <string>URL</string>
            <key>OutputUUID</key>
            <string>33333333-3333-4333-8333-333333333333</string>
            <key>Type</key>
            <string>ActionOutput</string>
          </dict>
          <key>WFSerializationType</key>
          <string>WFTextTokenAttachment</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.delay</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFDelayTime</key>
        <integer>${waitSeconds}</integer>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.repeat.each</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>UUID</key>
        <string>55555555-5555-4555-8555-555555555555</string>
        <key>GroupingIdentifier</key>
        <string>44444444-4444-4444-8444-444444444444</string>
        <key>WFControlFlowMode</key>
        <integer>2</integer>
      </dict>
    </dict>
    <dict>
      <key>WFWorkflowActionIdentifier</key>
      <string>is.workflow.actions.comment</string>
      <key>WFWorkflowActionParameters</key>
      <dict>
        <key>WFCommentActionText</key>
        <string>全部本地任务深链已经按顺序打开完毕。</string>
      </dict>
    </dict>
  </array>
  <key>WFWorkflowClientVersion</key>
  <string>2700.0.4</string>
  <key>WFWorkflowHasOutputFallback</key>
  <false/>
  <key>WFWorkflowIcon</key>
  <dict>
    <key>WFWorkflowIconGlyphNumber</key>
    <integer>61440</integer>
    <key>WFWorkflowIconStartColor</key>
    <integer>431817727</integer>
  </dict>
  <key>WFWorkflowImportQuestions</key>
  <array/>
  <key>WFWorkflowMinimumClientVersion</key>
  <integer>900</integer>
  <key>WFWorkflowMinimumClientVersionString</key>
  <string>900</string>
  <key>WFWorkflowName</key>
  <string>${escapeXml(target.workflowName)}</string>
  <key>WFWorkflowOutputContentItemClasses</key>
  <array/>
  <key>WFWorkflowTypes</key>
  <array/>
</dict>
</plist>
`;
}

function resolveTargets(arg) {
  if (!arg) return [TARGETS["baba-farm"]];
  if (arg === "all") return Object.values(TARGETS);
  if (!TARGETS[arg]) {
    const names = Object.keys(TARGETS).join(", ");
    throw new Error(`Unknown target "${arg}". Expected one of: ${names}, all`);
  }
  return [TARGETS[arg]];
}

function buildTarget(target) {
  const config = JSON.parse(fs.readFileSync(target.configPath, "utf8"));
  const { urls, waitSeconds } = buildTaskUrls(config);
  if (!urls.length) throw new Error("No task URLs generated");
  const xml = buildShortcutXml(target, urls, waitSeconds);
  assertLocalOnlyXml(xml);
  fs.mkdirSync(path.dirname(target.outputPath), { recursive: true });
  fs.writeFileSync(target.outputPath, xml);
  console.log(`Generated ${target.outputPath}`);
  console.log(`Embedded local task URLs: ${urls.length}`);
  console.log(`Delay seconds: ${waitSeconds}`);
  console.log("Remote JSON actions: none");
}

function main() {
  for (const target of resolveTargets(process.argv[2])) {
    buildTarget(target);
  }
}

main();
